CREATE TABLE MOVIES(movie_id INT(10) NOT NULL AUTO_INCREMENT, movie_name VARCHAR(100) NOT NULL, year INT(4) NOT NULL,
director_id INT(5) AUTO_INCREMENT,  director_name VARCHAR(100) NOT NULL, PRIMARY KEY(Movie_id)); 

