CREATE TABLE Users (CREATE TABLE Users(userid INT(10) NOT NULL AUTO_INCREMENT,
 username VARCHAR(50) NOT NULL, password VARCHAR(50) NOT NULL,
fav_movie VARCHAR(50), fav_genre VARCHAR(50), fav_actor VARCHAR(50),
PRIMARY KEY(user_id));
